In [2]:
println("Hello World!\nI'm starting learning Coursera Julia")

Hello World!
I'm starting learning Coursera Julia


### Arithmetic Operators
- \* + / - ^

In [4]:
1 + 1 # = 2

2

### Julia

- Like **interpreted language** but not exactly. (Oposite: **Compiled language**)
    - Interpreted: Compile line by line
    - Compiled: Compile the whole code and then run the state.
- It is **Just-in-time compilation**. Compile tiny bits of code and then run them.
- **Base package** -> almost all of it is written in *Julia*.
- Adding packages

### IJulia

- Adding it:
    - ```Pkg.add("IJulia")```
    - ```using IJulia```
- Using it:
    - ```notebook()```

### REPL
- Read-Evaluate-Print Loop
- 

In [5]:
println("Hello, world!")

Hello, world!


### println
- ```println()```
- built-in function
- ```()``` : parantheses
- ```[]``` : brackets
- ```{}``` : braces

### "Hello, world!"
- An argument
- inside the quotation: String -> like a telephone
    - Strings are **immutable** -> cannot be chang

In [6]:
println(5 - 3.8)

1.2000000000000002


In [7]:
println("Hello" * " My World!")

Hello My World!


In [ ]:
println("Hello" * " Gogolli!" ^ 3)

Hello Gogolli! Gogolli! Gogolli!


### Arithmetical Expressions
- using numbers and operators
- State of order

In [28]:
1 - 2 + 3 - 4

-2

In [29]:
1 / 2 + 3 / 4

1.25

In [30]:
1 // 2 + 3 // 4

5//4

In [31]:
(1 / 2 + 3) / 4

0.875

### Operator Precedence
- Left to Right (For same orders)
- () -> ^ -> / * -> + -
- Don't make the code messy.
- For exponentiation, Right to Left

In [1]:
0.2 + 2 - 3 * 6.7 / 4 + (3 - 2) ^ 2

-1.8250000000000002

In [3]:
3 ^ 4 ^ 2

43046721

In [1]:
(3 ^ 4) ^ 2

6561

### Logical Expressions
* Logic: How to transform true sentences into other true sentences
* Computer Logic: Only can evaluate logical expressions
* Keywords: true, false (Two logical values)
* Logical Operators:
    1. ! : **NOT** -> Reversing
    2. &&: **AND** -> Only all trues
    3. ||: **OR**  -> Only have one true

In [1]:
!true

false

In [2]:
!false

true

In [3]:
println(true && true)
println(true && false)
println(false && true)
println(false && false)

true
false
false
false


In [4]:
println(true || true)
println(true || false)
println(false || true)
println(false || false)

true
true
true
false


### Comparison Operators
* < 
* \>
* ==
* !=

In [5]:
1 < 2

true

In [6]:
3 == 3.5

false

### Operator precedence for logical expressions
* parantheses ()
* Left to Right
* Arithmetics are higher than Logicals
    * *\* / + - ^* > *! || &&*

### & and |
* & : bitwise AND
* | : bitwise OR
* Workds on pairs of integers
* | and || or & and && are **different**

### Short-circuit evaluation of Logical Expressions
* ```false && ...``` is always ```false```
* ```true || ...``` is always ```true```
* This make the code more efficient.

In [7]:
5040 / 60

84.0

In [10]:
x = 2
3x^2 - 2x + 3

11

In [15]:
3 & 5 > 0
8 & 5 > 0

false

### Type System
- Julia is a strong type language.
- Most of the times, you can ignore the types in Julia.
- But in some cases, you cannot. Especially when you run a program and Julia throw an Error at you.
- What is a **Type**: Types are formats for *Storing information*
- Information are stored and are moved in 0 and 1s. By knowing what **format to use**, you could tell what sequence of zeros and ones meant:
    - 0001110100011111000001111100100011110000000101
- We store two things:
    1. **Information**
    2. Its **Type**
- **Where** do you store the types of a given information?
    - Only **Values** have *Types*

In [1]:
1 + 3 + 5

9

In [2]:
typeof(1)

Int64

In [3]:
typeof(1 + 3 + 5)

Int64

In [5]:
typeof("Hello, world!")

String

In [6]:
typeof("H")

String

In [7]:
typeof('H')

Char

In [8]:
typeof(1 + 3 + 5.)

Float64

- Julia is very senstive to types
- Julia will automatically assign types to any values you create

### Char & String
- **String**: a sequence of Characters.
- ASCII list: specifies 128 characters: only alphabetic
- Unicode: Other characters

In [12]:
println("α β")
println("\alpha \beta")
println("⋄")
println("⤠")

α β
lpha eta
⋄
⤠


- They are available through ***LATEX***
- All of them have ```Char``` type.
- In Julia, types have name with first letter start with **Capital Letters**

### Boolean
- George Boole: the first oen who suggest the logical values: ture, false
- In Julia, it occupies only 8 bits


In [13]:
typeof(true)

Bool

### Int64 & Float64
- Most Scientific and Technical computation depends on them.
- ```Float64```: is a floating point format for real numbers
- ```Int64```: Integers


In [14]:
typeof(2)

Int64

In [18]:
typeof(2.)

Float64

In [16]:
2.0 == 2

true

In [17]:
2.0 === 2       # Strict Comparison

false

- Comparing between them can be done.
- **Promotion rules** --> Conversion rules

### Abstract Types
- Till here, we talked about **Concrete types**
- *Suptertype*: ```Any``` for every types or ```Real``` for ```Float64```
- They are a way to grouping them together.
- The actual type of a *value* should be **concerete type**
- Why we use **Abstract types**:
    1. Some operations change the type of a value: --> abstract types guide these processes
    2. Functions operate on types --> when you specify to use an abstract type, you are giving it multiple concerte types
- Julia has a **tree of types**

### Variables
- Each variable in julia has:
    1. name
    2. value
    3. type
- How to create ```Array``` type and how to access to the values in it.
- How Variables gets their value and how variables is structured in Juila and why they can have **Abstract types**

### Array types
- Multidimenstional arrays:

In [30]:
println(Array{Int64}(undef, 3))
typeof(Array{Int64}(undef, 3))

[7, 140730448254128, 1929430127280]


Vector{Int64} (alias for Array{Int64, 1})

- ```Array{Int64}(undef, 3)```: creates a 3 x 1 array of integers.
- ```undef```: no value is supplied
    - But because Julia hates empty arrays, it supplies some numbers to the Array (Waste numbers)
- ```Array{Int64, 1}```: The ```1``` is the dimenstion, but ```3``` is the number of elements

In [31]:
Array{String}(undef, 3)

3-element Vector{String}:
 #undef
 #undef
 #undef

In [33]:
Array{Float64}(undef, 3)

3-element Vector{Float64}:
 9.532375526267e-312
 9.53237490343e-312
 0.0

In [34]:
Array{Bool}(undef, 3)

3-element Vector{Bool}:
 0
 1
 0

### Assignment
- How variables get their values
- Do not use ```==``` --> just for **Comparison**
- Use ```=``` for **Assignment**

In [36]:
greeting = "Hello, World!"

"Hello, World!"

In [37]:
println(greeting)

Hello, World!


In [38]:
a = 5       # a takes the value of 5
b = a       # b takes the value of a

5

### Valid variable name
- Almost any String with letter, number or a few other characters

In [40]:
سلام = 2
خداحافظ = 3
[سلام, خداحافظ]

2-element Vector{Int64}:
 2
 3

- Can also use **Underscore**
- Do not use **Underscore** or **other weired characters**

In [42]:
very_important!pay_attention = 2

2

### The three parts of a Julia Variable
- Variable = name + value -----> The ```=``` binds the name to the value
- Variable = name + value + type ----> The type is the type of its value
- We can write a function without knowing the type of the variable or value that we are giving it.

### Create a variable with Abstract type

In [57]:
abstractType = Array{Integer}(undef, 2, 3) # Integer is an Abstract type


2×3 Matrix{Integer}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [50]:
typeof(abstractType)


Matrix{Integer} (alias for Array{Integer, 2})

In [51]:
abstractType[2, 3]

UndefRefError: UndefRefError: access to undefined reference

In [52]:
abstractType[2, 3] = 2

2

In [53]:
abstractType[2, 3]

2

In [54]:
abstractType[2, 1]

UndefRefError: UndefRefError: access to undefined reference

In [55]:
abstractType

2×3 Matrix{Integer}:
 #undef  #undef  #undef
 #undef  #undef    2

In [56]:
abstractType[2, 1] = 5.3

InexactError: InexactError: Int64(5.3)

In [58]:
abstractType[2, 1] = "String"

MethodError: MethodError: Cannot `convert` an object of type String to an object of type Integer

Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number
   @ Base number.jl:6
  convert(::Type{T}, !Matched::T) where T
   @ Base Base.jl:84
  convert(::Type{T}, !Matched::AbstractChar) where T<:Number
   @ Base char.jl:185
  ...


In [61]:
abstractType2 = Array{Int64}(undef, 3, 4) # Int64 is a Concerte Type

3×4 Matrix{Int64}:
 140731121031920  1929412749808  1929412751088  1929412751728
   1929412750544  1929412751024  1929412751120  1929412751408
   1929412750768  1929412751056  1929412751280  1929412749936

In [62]:
abstractType2[2, 3]

1929412751120

### Functions
- How functions work
- built-in and user-defined functions
- Multiple dispatch

### Functions in Julia
- ```println()```

In [67]:
greeting = "Hello, World!"
println(greeting)

Hello, World!


- Functions: Get some **Input** and **Something heppen**
- Shoing a string on the screen, Generating a value

In [68]:
a, b, c = cos(0.3), log(2), abs(-1.22)

(0.955336489125606, 0.6931471805599453, 1.22)

- ```typeof()```: A function provides information about the type of a value or variable

### Command line help
- In Ijulia: ```?``` and then the topic ---> Give you the manual or information about the argument infornt of the ```?```

In [2]:
?sin

search: sin sinh sind sinc sinpi sincos sincosd sincospi asin using isinf asinh



```
sin(x)
```

Compute sine of `x`, where `x` is in radians.

See also [`sind`](@ref), [`sinpi`](@ref), [`sincos`](@ref), [`cis`](@ref), [`asin`](@ref).

# Examples

```jldoctest
julia> round.(sin.(range(0, 2pi, length=9)'), digits=3)
1×9 Matrix{Float64}:
 0.0  0.707  1.0  0.707  0.0  -0.707  -1.0  -0.707  -0.0

julia> sind(45)
0.7071067811865476

julia> sinpi(1/4)
0.7071067811865475

julia> round.(sincos(pi/6), digits=3)
(0.5, 0.866)

julia> round(cis(pi/6), digits=3)
0.866 + 0.5im

julia> round(exp(im*pi/6), digits=3)
0.866 + 0.5im
```

---

```
sin(A::AbstractMatrix)
```

Compute the matrix sine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the sine. Otherwise, the sine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> sin(fill(1.0, (2,2)))
2×2 Matrix{Float64}:
 0.454649  0.454649
 0.454649  0.454649
```


### Built-in Mathematical functions

- ```exp()```
- ```log()``` --> **Natural Logarithm**
- ```log10()``` --> **Logarithm to base 10**
- ```cos()```
- ```sin()```
- ```tan()```
- ```acos()```
- ```asin()```
- ```floor()```
- ```ceil()```
- ```rem()```
- ```round()```
- ```floor()```

### Multiple dispatch
- For example ```cos()```:

In [1]:
cos(1)

0.5403023058681398

In [3]:
cos(1.0)

0.5403023058681398

- In both cases we got ```Float64``` type. But we give it different types of values.
- A function name ---point to---> a code body
- For each **type input**, there is an unique **code body**. This means that there are **multiple code bodies** for ```cos()```.
- We call these multiple code bodies for one function, **Multiple Dispatch** : Multiple definitions as long as each definition accepts a different combinaiton of arguments.


In [10]:
methods(muladd)

# 20 methods for generic function "muladd" from Base:
  [1] muladd(x::BigFloat, y::BigFloat, z::BigFloat)
     @ Base.MPFR mpfr.jl:541
  [2] muladd(z::Complex, w::Complex, x::Complex)
     @ complex.jl:299
  [3] muladd(x::T, y::T, z::T) where T<:Union{Float16, Float32, Float64}
     @ float.jl:414
  [4] muladd(x::T, y::T, z::T) where T<:Number
     @ promotion.jl:515
  [5] muladd(x::Real, y::Real, z::Complex)
     @ complex.jl:346
  [6] muladd(x::Real, z::Complex, y::Number)
     @ complex.jl:342
  [7] muladd(z::Complex, w::Complex, x::Real)
     @ complex.jl:347
  [8] muladd(z::Complex, x::Real, y::Real)
     @ complex.jl:343
  [9] muladd(z::Complex, x::Real, w::Complex)
     @ complex.jl:344
 [10] muladd(x::Number, y::Number, z::Number)
     @ promotion.jl:459
 [11] muladd(A::Union{LinearAlgebra.Adjoint{<:Any, <:StridedMatrix{var"#s994"}}, LinearAlgebra.Transpose{<:Any, <:StridedMatrix{var"#s994"}}, StridedMatrix{var"#s994"}} where var"#s994"<:Number, B::Union{LinearAlgebra.Adjoint{<:Any, <:StridedMatrix{var"#s128"}}, LinearAlgebra.Transpose{<:Any, <:StridedMatrix{var"#s128"}}, StridedMatrix{var"#s128"}} where var"#s128"<:Number, z::Union{Number, AbstractVecOrMat})
     @ LinearAlgebra C:\Users\sepehrskysh12\AppData\Local\Programs\Julia-1.10.3\share\julia\stdlib\v1.10\LinearAlgebra\src\matmul.jl:207
 [12] muladd(x::LinearAlgebra.Adjoint{T, <:AbstractVector} where T, A::AbstractMatrix, z::Union{Number, AbstractVecOrMat})
     @ LinearAlgebra C:\Users\sepehrskysh12\AppData\Local\Programs\Julia-1.10.3\share\julia\stdlib\v1.10\LinearAlgebra\src\matmul.jl:195
 [13] muladd(x::LinearAlgebra.Transpose{T, <:AbstractVector} where T, A::AbstractMatrix, z::Union{Number, AbstractVecOrMat})
     @ LinearAlgebra C:\Users\sepehrskysh12\AppData\Local\Programs\Julia-1.10.3\share\julia\stdlib\v1.10\LinearAlgebra\src\matmul.jl:197
 [14] muladd(u::AbstractVector, v::Union{LinearAlgebra.Adjoint{T, var"#s994"}, LinearAlgebra.Transpose{T, var"#s994"}} where {T, var"#s994"<:(AbstractVector)}, z::Union{Number, AbstractArray})
     @ LinearAlgebra C:\Users\sepehrskysh12\AppData\Local\Programs\Julia-1.10.3\share\julia\stdlib\v1.10\LinearAlgebra\src\matmul.jl:182
 [15] muladd(A::LinearAlgebra.Diagonal, B::LinearAlgebra.Diagonal, z::LinearAlgebra.Diagonal)
     @ LinearAlgebra C:\Users\sepehrskysh12\AppData\Local\Programs\Julia-1.10.3\share\julia\stdlib\v1.10\LinearAlgebra\src\diagonal.jl:909
 [16] muladd(A::LinearAlgebra.UniformScaling, B::LinearAlgebra.UniformScaling, z::LinearAlgebra.UniformScaling)
     @ LinearAlgebra C:\Users\sepehrskysh12\AppData\Local\Programs\Julia-1.10.3\share\julia\stdlib\v1.10\LinearAlgebra\src\uniformscaling.jl:430
 [17] muladd(A::Union{LinearAlgebra.Diagonal, LinearAlgebra.UniformScaling}, B::Union{LinearAlgebra.Diagonal, LinearAlgebra.UniformScaling}, z::Union{LinearAlgebra.Diagonal, LinearAlgebra.UniformScaling})
     @ LinearAlgebra C:\Users\sepehrskysh12\AppData\Local\Programs\Julia-1.10.3\share\julia\stdlib\v1.10\LinearAlgebra\src\special.jl:273
 [18] muladd(A::Union{LinearAlgebra.Adjoint{<:Any, <:StridedMatrix{var"#s994"}}, LinearAlgebra.Transpose{<:Any, <:StridedMatrix{var"#s994"}}, StridedMatrix{var"#s994"}} where var"#s994"<:Number, y::AbstractVector{<:Number}, z::Union{Number, AbstractVector})
     @ LinearAlgebra C:\Users\sepehrskysh12\AppData\Local\Programs\Julia-1.10.3\share\julia\stdlib\v1.10\LinearAlgebra\src\matmul.jl:200
 [19] muladd(A::AbstractMatrix, y::AbstractVecOrMat, z::Union{Number, AbstractArray})
     @ LinearAlgebra C:\Users\sepehrskysh12\AppData\Local\Programs\Julia-1.10.3\share\julia\stdlib\v1.10\LinearAlgebra\src\matmul.jl:168
 [20] muladd(x, y, z)
     @ Base.Math math.jl:1517

- ```methods()```: shows the different code bodies each function has.
    - ```T```: it is stand for **Type**
    - ```T<:Number```: saying that it can be a subtype of ```Number``` supertype, any number
    - ```T::Number```: saying that it should be a number, any number
    - You might think that these two are the same:
        1. ```muladd(x::T, y::T, z::T) where T<:Number in Base at promotion.jl:515```
        2. ```muladd(x::Number, y::Number, z::Number) in Base at promotion.jl:459```
        - However, they are not the same. For the first one, All of them are the same: ```T``` (for example: ```Int64``` only.)
        - But the second one give you the information that, the types of ```x```, ```y``` and ```z``` can have different types, but all of their types are the subtypes of ```Number```.

In [9]:
muladd(2, 3, 4)

10

- Many of the **ERROR**s are arise from the fact that: -------> There are no **Method**, no **Signature** that fit the types that we give as inputs
- Try:
    - Make sure that input values are the **right type signature**
    - If there is *no right type signature*, **Write an additional method** for the required type signature
    

### User-Defined Functions
- Defining **One-line syntax function**
- Defining **Multiline syntax function**
- Defining **Additional method for existing user-defined function**
- Specify Types for **input values**

### One-line Function
- The form:
```julia
myfunc(firstvar) = argument
```

In [11]:
myFunc(v) = 20 * v      # There is a method now for myFunc

myFunc (generic function with 1 method)

- The **Rules**:
    1. The name of the function -----> valid variable name
    2. The argument of the function ---> valid variable name
    3. The argument ----> inside teh parantheses (Multiple arguments seperated by comma)
    4. name, argument ---> variable, code body

In [13]:
myFunc(4.5)

90.0

In [14]:
addxtoy(x, y) = x + y

addxtoy (generic function with 1 method)

In [22]:
addxtoy(33., -22.2)

10.8

### Multiline Functions
- Contain:
    1. name and arguments
    2. code body
    3. end statement
```julia
function nextfunc(a, b, c)
    a * b + c
end
```
- There is a key word for writing functions: ```function```
- Then we use the **name of the function**.
- The **Arguments** are inside the parantheses.
- **All the codes** are called **Code Body**
- The ```end``` statement at the End!!!

In [23]:
function nextFunc(a, b, c)
    a * b + c
end

nextFunc (generic function with 1 method)

In [24]:
nextFunc(3, 4, 5)

17

- For ```println()```, when we use ```String```, we can use ```$``` in ```String```s to recall a value of a variable.

In [37]:
function showDebugPrintln(testvar)
    println("Inside the showDebugPrint() now:")
    println("The type of testvar is $(typeof(testvar)) and the value testvar is $testvar")
end

showDebugPrintln (generic function with 1 method)

In [38]:
showDebugPrintln('1')

Inside the showDebugPrint() now:
The type of testvar is Char and the value testvar is 1


In [39]:
a =["Sepehr", 2//4]
showDebugPrintln(a)

Inside the showDebugPrint() now:
The type of testvar is Vector{Any} and the value testvar is Any["Sepehr", 1//2]
